# Project information
site_name: PyTank
site_url: http://pytank-doc.readthedocs.io/
site_author: Kevin Lopez
site_description: >-
  Python + Reservoir Engineering = Pytank
  Estimate hydrocarbon reserves with this tool, implementing material balance.

# Repository
repo_name: ESPOL-FICT/PYTANK
repo_url: https://github.com/kelosori/Pytank-Doc.git


# Copyright
copyright: Copyright &copy; 2024 Kevin Lopez

# Configuration
theme:
  name: material
  # custom_dir: pydoc/overrides
  features:
    - announce.dismiss
    - content.action.view
    - content.action.edit
    - content.action.annotate
    - content.action.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.expands
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-6
        name: Switch to system preference
  font:
    text: Ubuntu
    code: Ubuntu
  favicon: static/Icon 2.ico
  logo: static/Icon.png

# Plugins
plugins:
  - mkdocstrings
  - mkdocs-jupyter
  - search

# Additional configuration
extra:
  homepage: http://pytank-doc.readthedocs.io/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kelosori
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/Pytank/

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: false


# Page tree
nav:
  - Home: index.md
  - Getting Started: nav/getting_started.md
  - User Guide:
      - Setup:
          - User Guide: nav/setup/user_guide.md
          - Quick Starter: nav/setup/quick_starter.ipynb
          - Advanced Features: nav/setup/advance_features.ipynb
      - Create Your Items:
          - How to Create a Well?: nav/setup/well.md
          - Fluid Models Needed: nav/setup/fluid_model.md
          - How to Create a Tank?: nav/setup/tank.md
          - Analyzing with PyTank: nav/setup/analysis.md
          - Creating an Aquifer: nav/setup/aquifer.md
  - Development:
      - Development Guide: nav/develop/develop_guide.md
      - Release Notes: nav/develop/release_notes.md
  - API Reference:
      - Overview: nav/API/api_reference.md
      - Main Modules:
          - Well: nav/API/generated/well_api.md
          - Fluid Model: nav/API/generated/fluid_model_api.md
          - Oil Model: nav/API/generated/oil_model.md
          - Water: nav/API/generated/water_model.md
          - Tank: nav/API/generated/tank_api.md
          - Aquifer: nav/API/generated/aquifer_api.md
          - Analysis: nav/API/generated/analysis_api.md
      - Secondary Modules:
          - Helpers: nav/API/generated/helpers.md
          - Vectors: nav/API/generated/vector_data.md
      - Additional Resources:
          - PVT Correlations: nav/API/generated/pvt_correlations.md
          - Material Balance: nav/API/generated/mb_api.md
          - Utilities: nav/API/generated/utilities.md




extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_HTML
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js