site_name: PyTank

nav:
  - Home: index.md
  - Getting Started: nav/getting_started.md
  - User Guide:
      - nav/setup/user_guide.md
      - nav/setup/quick_starter.ipynb
      - nav/setup/advance_features.ipynb
      - Create your items:
          - How to create a Well?: nav/setup/well.md
          - Which fluid models do I need?: nav/setup/fluid_model.md
          - How to create a Tank?: nav/setup/tank.md
          - Analyzing with Pytank: nav/setup/analysis.md
          - Let´s create an Aquifer: nav/setup/aquifer.md
  - Development:
      - nav/develop/develop_guide.md
      - nav/develop/release_notes.md
  - API reference:
      - Overview: nav/API/api_reference.md
      - Main Modules:
          - Well: nav/API/generated/well_api.md
          - Fluid Model: nav/API/generated/fluid_model_api.md
          - Oil Model: nav/API/generated/oil_model.md
          - Water: nav/API/generated/water_model.md
          - Tank: nav/API/generated/tank_api.md
          - Aquifer: nav/API/generated/aquifer_api.md
          - Analysis: nav/API/generated/analysis_api.md
      - Secondary Modules:
          - Helpers: nav/API/generated/helpers.md
          - Vectors: nav/API/generated/vector_data.md
      - Others:
          - PVT Correlations: nav/API/generated/pvt_correlations.md

theme:
  name: material
  favicon: ../static/Icon 2.ico
  logo: ../static/Icon.png
  theme_style: light
  site_name_style: normal
  title_style: bold
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: false
    menu: true
    preview: true
    footer: true

plugins:
  - mkdocstrings
  - mkdocs-jupyter

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: false
  - pymdownx.tabbed:
      alternate_style: true

extra:
  homepage: index.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_HTML